# LLM API配置
llm:
  api_url: "http://localhost:11434/v1/chat/completions"  # API地址
  model_name: "deepseek-r1:latest"  # 模型名称
  api_key: ""  # API密钥（如果需要）
  timeout: 3000  # 请求超时时间（秒）增加到3000秒
  max_retries: 5  # 最大重试次数增加到5次
  temperature: 0.7  # 温度参数

# 文件路径配置
paths:
  input_dir: "file"  # 输入文档目录
  output_dir: "output"     # 输出目录

# 文件处理配置
processing:
  supported_extensions:    # 支持的文件类型
    - .md
    - .docx
    - .pdf
    - .xlsx
    - .xls
  questions_per_file: 10   # 每个文件生成的问题总数

# 输出配置
output:
  csv_filename_template: "qa_pairs_{timestamp}.csv"  # CSV文件名模板
  excel_filename_template: "qa_pairs_{timestamp}.xlsx"  # Excel文件名模板

# 提示词配置
prompts:
  system_prompt_template: |
    你是一个专业的文档分析助手。你的任务是：
    1. 仔细阅读提供的文档内容
    2. 提出{questions_count}个与文档内容相关的重要问题
    3. 对每个问题，从文档中提取相关信息作为答案
    4. 确保问题和答案都是清晰、准确且相关的
    5. 以JSON格式返回结果，格式为：[{{"question": "问题1", "answer": "答案1"}}, ...]
    6. 只返回JSON格式的数据，不要包含任何其他内容
  user_prompt_template: "请分析以下文档内容并生成问答对：\n\n{text}" 